language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dNXDayKS5l4UfWfcVDHOD7cQd0W51WzOfeq7gFYrtZam0j4Ezppu/a/RIQeL/NFY4Lx/MQg+D+Bx64NerN+0eAONKFfDbpkhdKqchXUaToICQaoplRP+jbBK2R0W2711xX+uACr0pCo45eN8SIXMsfEHCyPjJF3JdiTDLxKUa2t57SJaoRXGz3oTFpH9Nt/wsLGLh94RPWGyM/olXpmAtw/4hUlPBZhSDRM4FC5BpaGoXAdBrRmyNMgNeE6+JEJL7WFTzBd4+l41FEFoHm95kxanieCvge/z2A8SL/mXoXGsE27EfCN694fe4rLiAMzwAxOkQPFHuBJ5gKoO2OqUpCa0/sznsEzBAyg3auXG0++19XdD8sLX/g2teGOvxNugeXHxzWGtOEW2tqOnEpp59r3jn14g+bgxc+XLYo53R2Dsr4KTpILq0PoWxchkn0v4uExMtW+xs6+V8FvE4748n+Q7q1XUkK79y7KCGaqLD1b9wR/L8bRVKbrQsagNwQWBFs8qPiUQMmYfAoQHyWgaeE6CSga0IWV+nyQ/7fYLfNdSryB1KzHVaqbm6iUMNx50DTvbOiKgOIIz9SZhtlbyRVTNkUqZiZghy4c1VlzBSCJALxPasEobEMthL5sZE5Lq4+3dFDJnIWMQ6y6BGeZ4mOd7ZSg9Pgs2fSdbwB/LamI=
  file:
    - "retext-spell.js"
    - "retext-spell.min.js"
  on:
    tags: true
    node: '9.0'
